import checkUser from './checkUser'
import Footer from '../components/footer'
import Nav from '../components/nav'
import NavMobile from '../components/navMobile'

const Privacy = ({loggedIn}) => {
  
  return (
    <>
    <Nav loggedIn={loggedIn}></Nav>
    <NavMobile loggedIn={loggedIn}></NavMobile>
    <div className="terms">
      <div className="terms-container">
        <div className="terms-title">Privacy Policy</div>
        <p>
        Significard Inc., a Delaware corporation ("Significard", "we", "us" or "our") is committed to maintaining the confidentiality, integrity, and security of personal information, if any, collected from our users. When you use Significard, you trust us with your information. This Privacy Policy is meant to help you understand what data we collect, why we collect it, and what we do with it. This is important; we hope you will take time to read it carefully. 
        </p>
        <p>Significard offers a technology platform that enables users of Significard’s Sites provided as part of the Services (each an “Application”) to arrange and schedule handwriting and/or logistics services with third party providers of such services, including independent third party providers, partners or affiliates of Significard (the "Services") to let you order cards with your messages handwritten in them and sent via postal service. As used in this Privacy Policy, the term "Site" or “Sites'' includes all applications, content, products and services that we operate, including pages within each site, device or application and any equivalent, mirror, replacement, substitute or back up site, device or application and the pages associated with the same. The use of the word "including" or “includes'' in this Privacy Policy to refer to specific examples means "including, without limitation" or "including but not limited to" and does not mean that the examples given are an exclusive list of the topics covered.</p>
        <p>This Privacy Policy explains the privacy practices we have adopted to protect our users' personal information collected from our Sites. Significard's privacy and security standards are intended to help guard against identity theft and provide security for your personal information. In addition to this Privacy Policy, we have established Terms of Service that set forth the general rules and policies governing your use of the Sites.</p>
        <p>By using a Site and/or providing us your personal information, you signify your assent to this Privacy Policy. If you do not agree with any term in this Privacy Policy, please do not provide us your personal information or use the Sites. Please note: The laws and regulations in different countries impose different (and even conflicting) requirements on the Internet and data protection and many of such laws are rapidly evolving. The servers that make the Sites available worldwide are located in the United States. All matters relating to the Sites are governed by the laws of the state of Delaware, without reference to its conflicts of law rules that would result in the application of the laws of another jurisdiction. Please note that any information you provide will be transferred to the United States, and by using the Site or providing us your personal information, you authorize this transfer. </p>
        <div className="terms-subtitle">1. How We Use Your Information</div>
        <p>We may use and disclose your personal information only as follows: a) to analyze Site usage and improve the services provided through the Sites (the "Services"); b) to deliver to you any administrative notices or alerts and communications; c) relevant to your use of the Services; d) to fulfill your requests for certain products and Services; e) for market research, project planning, troubleshooting problems; f) detecting and protecting against errors, fraud, or other criminal activity; g) in connection with a merger, sale of substantially all of our assets, or corporate reorganization; and h) to enforce our Terms of Service and as otherwise set forth in this Privacy Policy. Except as noted above, we do not and will not share, sell or rent your personal information to anyone, for any reason, at any time.</p>
        <div className="terms-subtitle">2. THE INFORMATION WE COLLECT. </div>
        <p>Significard may collect the following categories of personal information about you through the Sites: a) Registration Information: When you register for a Service, you will be asked for basic registration information, such as an email address and password; b) Identification Information: You may also be asked to provide identification information to confirm your identity, including your first and last name, zip code and phone number. When you request a service, we collect billing information such as credit card number, and billing address. We use this information for the sole purpose of billing for your membership. We do not store billing details; we leverage a third party provider. We also collect and store any content that you choose to enter in connection with your use of the Services. As technology evolves, we may also collect other types of information, consistent with this Privacy Policy and our Terms of Use. Safeguarding information to help protect you from identity theft is a top priority. We do not and will not, at any time, request your credit card information, your login information, or national identification numbers in an unsolicited e-mail or telephone communication.</p>
        <p>We may receive information about you from other sources. We may add this information to the information we have already collected from you via our Services in order to improve and market the Services.</p>
        <p>The Services allow users to share information with us via social networking sites, such as Facebook, Instagram, or LinkedIn (each an “SNS”). In some cases, you can sign-in to the Services using your SNS account information. By sharing your SNS profile, you are allowing us to access some of your SNS information depending on your SNS settings or as allowed by you (such as profile information and profile photo). We may receive that information from your SNS profile and that information may be imported to the Services. Our Services also allow you to share information via such SNS profiles. You acknowledge and agree that you are solely responsible for your use of SNSs and that it is your responsibility to review the terms of use and privacy policy of the third party provider of such SNSs. We will not be responsible or liable for: (i) the availability or accuracy of such SNSs; (ii) the content, products or services on or availability of such SNSs; or (iii) your use of any such SNSs. You can remove your SNS profile information by contacting us. </p>
        <div className="terms-subtitle">3. WE PROTECT THE INFORMATION WE COLLECT.</div>
        <p>We take very seriously the privacy of your personal information. We use firewall barriers and authentication procedures, among others, to maintain the security of your online session and to protect Significard accounts and systems from unauthorized access. We may also place cookies and similar files on your device for purposes such as security, to facilitate site navigation, and to personalize your experience on our Site and if so, such cookies will not identify you by name as an individual or by account number except as described in this Privacy Policy. Any cookies that may be used will not identify you by name as an individual or by account number except as described in this Privacy Policy. See the "How we use cookies'' section below for more information. Safeguarding information to help protect you from identity theft is a top priority. We do not and will not, at any time, request your credit card information, your login information, or national identification numbers in an unsolicited e-mail or telephone communication.</p>
        <div className="terms-subtitle">4. HOW WE USE THE INFORMATION WE COLLECT:</div>
        <p>We may use the information you provide about yourself to fulfill your requests for our products, programs, and Services, to respond to your inquiries about our Services, and to offer you other products, programs, or services that we believe may be of interest to you. In order to allow you to use certain Services, we may be required to verify your identity. We may also use your information to verify your identity in the event you contact us for assistance with the Sites or Services. In certain situations, we may use or share your personal information: a) to respond to subpoenas, court orders, or legal process; b) in order to investigate, prevent, defend against, or take other action; c) regarding violations of our Terms of Service, illegal activities, suspected fraud, or situations involving potential threats to the legal rights or physical safety of any person or the security of our network, Sites or Services; d) to respond to claims that any posting or other content violates the rights of third parties; e) in an emergency, to protect the health and safety of our Sites' users or the general public; or f) as otherwise required by law. </p>
        <p>We may outsource some tasks to affiliated companies or third parties and may share your information with those companies or third parties if reasonably necessary to enable them to assist in fulfilling the requests you make or the transactions you conduct via the Sites, including the operation of certain Site functions and Services that require access to information you supply online. In such cases, if such affiliated companies or third parties acting on our behalf are given access to the information you have supplied to us, we require that the companies abide by our privacy policy and institute safeguards to protect the confidentiality of your information. Your information is provided to third party writers accessing our Sites to fulfill certain Services such as handwriting and delivery to a postal service for payment in connection with the Services. </p>
        <p>We may use your information for internal analysis such as analyzing user behavior in aggregate for research and marketing purposes. Significard may also aggregate transaction data and disclose such data only in aggregate and in a non-personally identifiable manner to third parties for marketing and promotional purposes (e.g., how many users responded to a particular offer). Aggregated information does not identify you individually.</p>
        <p>When you visit our Sites, we may collect technical and navigational information, such as computer browser type, Internet protocol address, pages visited, and average time spent on our Site. This information may be used, for example, to alert you to software compatibility issues, or it may be analyzed to improve the design and functionality of our Sites.</p>
        <p>Any feedback, questions, comments, suggestions, ideas, or the like that you send to Significard will be treated as being non- confidential and nonproprietary, and Significard will be free to use such information for any purpose whatsoever including, but not limited to, developing, manufacturing, and marketing products and services incorporating the information. If our company or our assets are acquired by another company, or in the event of a merger, consolidation, change in control, transfer of substantial assets, reorganization, or liquidation, we may transfer, sell, or assign to third parties information concerning your relationship with us, including, without limitation, personally identifiable information that you provide and other information concerning your relationship with us. Such third parties will assume responsibility for the personal information collected by us in connection with our business operations or through our Sites and such third parties will assume the rights and obligations regarding such information as described in this Privacy Policy.</p>
        <div className="terms-subtitle">5. EMAILS FROM WHICH YOU MAY "OPT-OUT":</div>
        <p>Significard complies with the Controlling the Assault of Non-Solicited Pornography and Marketing Act of 2003. Significard provides users periodic Site-related notifications, newsletters, or other information. Users may elect to stop receiving such messages at their discretion. If you no longer wish to receive periodic updates from Significard, you may update your account preferences on the Site. You may also follow the unsubscribe instructions included in each promotional email. However, please note that certain Services-related messages that we send users are necessary for the proper functioning and use of the Services, and users who participate in such Services do not have the ability to opt-out of such messages.</p>
        <div className="terms-subtitle">6. COLLECTION OF INFORMATION BY THIRD PARTIES AND SPONSORS:</div>
        <p>In certain cases, you may be directed to a third party site to provide information to complete a transaction in connection with one of our Sites. In such cases, any information you provide to such third party sites directly to such third party will be subject to the applicable third party's privacy policy and terms of service. Additionally, the Sites may contain links to other sites whose information practices may be different than ours. Visitors should consult the other sites' privacy notices, as we have no control over information that is submitted to, or collected by, these third parties.</p>
        <p>The Sites may contain third party advertisements or offers that are complementary to your use of Significard that may be custom matched to you based on information you provided to the Site, queries made through the Site or other information. If you choose to use these separate products or services, disclose information to the providers, or grant them permission to collect information about you, then their use of your information is governed by their privacy policies. You should evaluate their practices before deciding to use their services. </p>
        <p>SIGNIFICARD DOES NOT CONTROL AND IS NOT RESPONSIBLE FOR WHAT THIRD PARTIES DO IN CONNECTION WITH THEIR WEBSITES, OR HOW THEY HANDLE YOUR PERSONAL INFORMATION. PLEASE EXERCISE CAUTION AND CONSULT THE PRIVACY POLICIES POSTED ON EACH THIRD PARTY WEBSITE FOR FURTHER INFORMATION. </p>
        <p>We may use third party service providers to help us analyze certain activities. For example, these service providers may help us measure the performance of our promotions or determine Site activity. We do not share any personally identifiable information about our users with these third parties, and these third parties do not collect such information on our behalf. Additionally we may utilize third party ad serving networks and their associated tracking functionality to deliver more targeted advertising to our users and to optimize customer acquisition efforts.</p>
        <div className="terms-subtitle">7. HOW WE MAY USE COOKIES:</div>
        <p>To enhance your experience with our Sites, our pages may use "cookies." Cookies are text files that are placed on your device to store your preferences or for other record-keeping purposes. Cookies and other user tracking mechanisms (e.g., local shared objects), by themselves, do not tell us your personally identifiable information unless you choose to provide this information to us by, for example, registering at our Site. However, once you choose to furnish us with personally identifiable information, this information may be linked to the data stored in the cookie or other tracking mechanism. We may use cookies and other user tracking mechanisms, including "persistent cookies", which will remain on your device even after you close your browser, to understand Site usage and to improve the content and offerings on our Sites. For example, we may use cookies to personalize your experience at our Site (e.g., to recognize you by name when you return to our Site), and to save your password in password-protected areas. We also may use cookies to offer you products, programs, or services. While most browsers are set to accept cookies and other tracking devices by default, you can set yours to refuse tracking devices or to alert you before accepting them. However, by disabling tracking devices, you may not have access to the entire set of features of our Sites. Your browser manufacturer has information on changing the default setting for your specific browser. </p>
        <p>Significard may use standard Internet technology, such as web beacons and similar technologies, to track your use of the Site or to track your response to messages that we send you in connection with the Sites or Services. Web beacons (sometimes called transparent GIFs, clear GIFs, or web bugs) are small strings of code that provide a way for us to deliver a small graphic image (usually invisible) on a web page or in a notification. Web beacons can recognize certain types of information on your device such as cookies, the time and date a page is viewed, and a description of the page where the web beacon is placed. Significard may use web beacons to improve your experience on the Site, including to provide you with content customized to your interests and to understand whether users read messages and click on links contained within those messages so that the Site can deliver relevant content. Our web beacons may collect some contact information (for example, the address associated with a notification that contains a web beacon). The Sites also may include third-party web beacons so that these third parties may receive auditing, research, and reporting information about advertisements viewed on the Site. </p>
        <div className="terms-subtitle">8. NO GUARANTEES:</div>
        <p>While this Privacy Statement expresses Significard's standards for protection of personally identifiable information, Significard is not in a position to guarantee that the standards will always be met. There may be factors beyond our control that may result in unintentional disclosure of data. We follow generally accepted industry standards to protect the personal information submitted to us, both during transmission and once we receive it. No method of transmission over the Internet, or method of electronic storage, is 100% secure, however. Therefore, while we strive to use commercially acceptable means to protect your personal information, we cannot guarantee its absolute security and are not responsible for the theft, destruction, or inadvertent disclosure of your personally identifiable information. In the unfortunate event that your "personally identifiable information" (as the term or similar terms are defined by any applicable law requiring notice upon a security breach) is compromised, we may notify you by email (at our sole and absolute discretion) to the last contact information you have provided us in the most expedient time reasonable under the circumstances; provided, however, delays in notification may occur while we take necessary measures to determine the scope of the breach and restore reasonable integrity to the system as well as for the legitimate needs of law enforcement if notification would impede a criminal investigation. </p>
        <div className="terms-subtitle">9. OWNERSHIP OF DATA AND CHANGES TO YOUR PERSONAL INFORMATION: </div>
        <p>Your data belongs to you, and you can remove it anytime you want. To cancel your Significard account and delete all account information associated with your account, please contact us at hello@significard.com If you ask us to delete your account, we will use commercially reasonable efforts to remove your data from our servers. Despite such removal, portions of your data may remain on our production and back-up servers indefinitely. </p>
        <p>If you wish to access personal information that you have submitted to us or to request the correction of any inaccurate information you have submitted to us, you may correct certain information via your user account. Alternatively, you can send an email that includes your contact information to hello@significard.com to request any corrections to your personal information.</p>
        <div className="terms-subtitle">10. CHANGES TO THIS PRIVACY POLICY: </div>
        <p>We regularly re-evaluate our privacy and security policies and adapt them as necessary to deal with new challenges. We reserve the right, at our discretion, to make changes to this Privacy Policy from time to time, so please review it frequently. You may review updates to our Terms of Service and Privacy Policy at any time via links on www.significard.com. You agree to accept electronic communications and/or postings of revised versions of this Privacy Policy on www.significard.com and agree that such electronic communications or postings constitute notice to you of the revised version of this Privacy Policy. If we make material changes to this Privacy Policy, we will notify you here, by email or by posting a notice on our home page. </p>
        <div className="terms-subtitle">GOT QUESTIONS? </div>
        <p>If you have questions or concerns regarding this statement, or if you have any questions or suggestions, you should first contact hello@significard.com. </p>
      </div>
    </div>
    <Footer loggedIn={loggedIn}></Footer>
    </>
  )
}

export default checkUser(Privacy)
